version: '2.4'
services:
  ui:
    image: registry.planr.cloud/site/planr-site-ui:26.7.16
    mem_limit: 512m
    # Traefik подключён к внешней сети site_default 
    networks:
      - site_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=site_default"
      - "traefik.http.routers.planr-site-ui.rule=Host(`planr.cloud`)"
      - "traefik.http.routers.planr-site-ui.entrypoints=websecure"
      - "traefik.http.routers.planr-site-ui.tls.certresolver=myresolver"
      - "traefik.http.services.planr-site-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.planr-site-ui.middlewares=traefik-compress"

networks:
  site_default:
    external: true
